### ISSUE TITLE
smartnode status gives back error -32603

### ISSUE THREAD

**Issue by bluetyphoon77** [SmartCash/Core-Smart#89]
-->
error code: -32603
error message:
This is not a smartnode

Why is that ? I installed the coresmart wallet, last version to set up my MN manually
Thanks a lot

**Comment by angelovdb** [comment]
I do think this is a dead project.
I also created a MN but went in error on nodehub.

**Comment by thesolarminer** [comment]
I already replied to bluetypoon77 in discord shortly after the first post, but will reply again here to be clear.

The error above was due to the smartnode=1 in the config file without a smartnode private key.  

If nodehub has an issue, they can ask for help in setting up their node in discord.

We have a script that sets up a node and fills in most of the configuration here.
https://github.com/SmartCash/SmartInstall
